Listing/urls.py
from django.urls import path

from .views import product_list, product_detail,search_product
app_name = 'Listing'

urlpatterns = [

    path('', product_list, name='product_list'),
    path('search',search_product,name='product_search'),
    path('<slug:category_slug>', product_list, name='product_list_by_category'),
    path('<slug:category_slug>/<slug:product_slug>', product_detail, name='product_detail'),
]

Store/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import logout
if settings.DEBUG:
    urlpatterns = [
        path('ticket/', include('support.urls', namespace='ticket')),
        path('api/',include('api.urls', namespace='ticketss')),
        path('login/', include('social_django.urls', namespace='social')),

        path('auth1/', include('djoser.urls')),
        path('auth2/', include('djoser.urls.jwt')),

        path("account/", include("account.urls")),
        path('admin/', admin.site.urls),
        path('cart/', include('cart.urls', namespace='cart')),
        path('orders/', include('orders.urls', namespace='orders')),

        path('', include('Listing.urls', namespace='listings')),

    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from . import views
from rest_framework import routers
app_name = 'ticketss'

router = routers.SimpleRouter()

router.register('ticket', views.TicketViewSet, basename='create')
router.register('message',views.MessageViewSet, basename='message')
router.register('product',views.ProductViewSet,basename='product')
router.register('category',views.CategoryViewSet,basename='category')
router.register('order',views.OrderViewSet,basename='order')
urlpatterns = router.urls

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views
app_name='orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('logout/', views.logout_view, name='logout'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms




PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(min_value=1)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect


from .forms import CartAddProductForm

from Listing.models import Product
from decimal import Decimal


def get_cart(request):
    cart = request.session.get(settings.CART_ID)
    if not cart:
        cart = request.session[settings.CART_ID] = {}
    return cart


def cart_add(request, product_id):
    cart = get_cart(request)

    product = get_object_or_404(Product, id=product_id)
    product_id = product.id
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        if product_id not in cart:
            cart[product_id] = {'quantity': 0, 'price': str(product.price)}

        if request.POST.get('overwrite_qty'):
            cart[product_id]['quantity'] = cd['quantity']
        else:
            cart[product_id]['quantity'] += cd['quantity']

        request.session.modified = True

    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = get_cart(request)
    product_ids = cart.keys()
    products = Product.objects.filter(id__in=product_ids)
    temp_cart = cart.copy()
    cart_total_price = 0

    for product in products:
        cart_item = temp_cart[str(product.id)]
        cart_item['product'] = product
        cart_item['total_price'] = (Decimal(cart_item['price']) * cart_item['quantity'])
        cart_total_price = sum(Decimal(item['price']) * item['quantity'] for item in temp_cart.values())

        cart_item['update_quantity_form'] = CartAddProductForm(initial={'quantity': cart_item['quantity']})

    return render(request, 'cart/detail.html', {
        'cart': temp_cart.values(),
        'cart_total_price': cart_total_price
    })


def cart_remove(request, product_id):
    cart = get_cart(request)
    product_id = str(product_id)
    if product_id in cart:
        del cart[product_id]
        request.session.modified = True
    return redirect('cart:cart_detail')


def cart_clear(request):
    del request.session[settings.CART_ID]

templates/cart/detail.html
{% extends 'base.html' %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
    <h1>Your shopping cart</h1>
<style>
* {
    box-sizing: border-box;
}

body {
    margin: 0;
    font-family: Arial;
    font-size: 17px;
}

#myVideo {
    position: fixed;
    right: 0;
    bottom: 0;
    min-width: 100%;
    min-height: 100%;

    z-index: 1;

}
.card {
    background-color:rgba(250,250,250,0.23);
    margin: 5px 5px 5px 5px;
    border: none;

}
.item-image{
    border-radius: 5px;
}
.content {
    display:flex;
    position: relative;
    bottom: 0;
    background: rgba(0, 0, 0, 0.5);
    color: #f1f1f1;
    width: 100%;
    padding: 20px;
    z-index: 2;
    border-radius: 20px;
}
.content-2{
    display: list-item;
}
.list-group-item{
    background: rgba(0, 0, 0, 0.5);
}
</style>
</head>
<body>

<video autoplay muted loop id="myVideo">
  <source src="/static/3.mp4" type="video/mp4">
  Your browser does not support HTML5 video.
</video>

<div class="content">

        {% for item in cart %}
            {% with product=item.product %}
               <div class="card" style="width: 18rem;">
                  <img class="card-img-top" src="{{ product.image.url }}" alt="Card image cap">
                  <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>

                  </div>
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item">Quantity {{ item.quantity }}</li>
                    <li class="list-group-item">{{ item.price }}$</li>
                    <li class="list-group-item"><a href="{% url "cart:cart_remove" product.id%}">Remove</a></li>
                  </ul>
                  <div class="card-body">
                    <a href="{{ product.get_absolute_url }}" class="card-link">Link</a>

                  </div>
                </div>


            {% endwith %}
        {% endfor %}

        </tbody>
    </table>

<div class="content-2">
    <button type="button" class="btn btn-secondary btn-lg btn-block"><a href="{% url "Listing:product_list" %}" style="color: white">Continue shopping</a></button>
    <button type="button" class="btn btn-secondary btn-lg btn-block"><a href="{% url "orders:order_create" %}"style="color: white">Checkout</a></button>
</div>
</div>
</body>
{% endblock %}