Listing/urls.py
from django.urls import path

from .views import product_list, product_detail,search_product
app_name = 'Listing'

urlpatterns = [

    path('', product_list, name='product_list'),
    path('search',search_product,name='product_search'),
    path('<slug:category_slug>', product_list, name='product_list_by_category'),
    path('<slug:category_slug>/<slug:product_slug>', product_detail, name='product_detail'),
]

Store/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import logout
if settings.DEBUG:
    urlpatterns = [
        path('ticket/', include('support.urls', namespace='ticket')),
        path('api/',include('api.urls', namespace='ticketss')),
        path('login/', include('social_django.urls', namespace='social')),

        path('auth1/', include('djoser.urls')),
        path('auth2/', include('djoser.urls.jwt')),

        path("account/", include("account.urls")),
        path('admin/', admin.site.urls),
        path('cart/', include('cart.urls', namespace='cart')),
        path('orders/', include('orders.urls', namespace='orders')),

        path('', include('Listing.urls', namespace='listings')),

    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from . import views
from rest_framework import routers
app_name = 'ticketss'

router = routers.SimpleRouter()

router.register('ticket', views.TicketViewSet, basename='create')
router.register('message',views.MessageViewSet, basename='message')
router.register('product',views.ProductViewSet,basename='product')
router.register('category',views.CategoryViewSet,basename='category')
router.register('order',views.OrderViewSet,basename='order')
urlpatterns = router.urls

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

templates/product/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ product.name }}{% endblock %}
{% block content %}
<style>
* {
    box-sizing: border-box;
}

body {
    margin: 0;
    font-family: Arial;
    font-size: 17px;
}

#myVideo {
    position: fixed;
    right: 0;
    bottom: 0;
    min-width: 100%;
    min-height: 100%;

    z-index: 1;

}
.card {
    background-color:rgba(250,250,250,0.23);
    margin: 5px 5px 5px 5px;
    border: none;

}
.item-image{
    border-radius: 5px;
}
.content {
    display:flex;
    position: relative;
    bottom: 0;
    background: rgba(0, 0, 0, 0.5);
    color: #f1f1f1;
    width: 100%;
    padding: 20px;
    z-index: 2;
    border-radius: 20px;
}


</style>
</head>
<body>

<video autoplay muted loop id="myVideo">
  <source src="/static/2.mp4" type="video/mp4">
  Your browser does not support HTML5 video.
</video>

<div class="">

<div class="content">
  <img src="{{ product.image.url }}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{ product.name}}</h5>
    <H2 class="card-text">{{ product.description }}</H2>
      <p class="card-text">{{ product.category}}</p>
    <p class="card-text"><small class="text-muted">Coast {{ product.price }}$</small></p>
      <p class="price">${{ product.price }}</p>
<form action="{% url 'cart:cart_add' product.id %}" method="post">
    {% csrf_token %}
    {{ cart_product_form }}
<button type="submit" class="btn btn-secondary btn-lg btn-block">Аdd product to cart</button>

</form>
  </div>
</div>
</div>
{% endblock content %}

templates/product/list.html
{% extends 'base.html' %}
{% block title %}Store{% endblock %}
{% block content %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
    box-sizing: border-box;
}

body {
    margin: 0;
    font-family: Arial;
    font-size: 17px;
}

#myVideo {
    position: fixed;
    right: 0;
    bottom: 0;
    min-width: 100%;
    min-height: 100%;

    z-index: 1;

}
.card {
    background-color:rgba(250,250,250,0.23);
    margin: 5px 5px 5px 5px;
    border: none;

}
.item-image{
    border-radius: 5px;
}
.content {
    display:flex;
    position: relative;
    bottom: 0;
    background: rgba(0, 0, 0, 0.5);
    color: #f1f1f1;
    width: 100%;
    padding: 20px;
    z-index: 2;
    border-radius: 20px;
}


</style>
</head>
<body>

<video autoplay muted loop id="myVideo">
  <source src="/static/1.mp4" type="video/mp4">
  Your browser does not support HTML5 video.
</video>
<div class="content">
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="/static/slide1.jpg" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="/static/slide2.jpg" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="/static/slide3.jpg" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
<div class="content">



    <div class="row justify-content-center">
        <div class="dropdown">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Product category
         </a>

    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <a class="dropdown-item" href="{% url 'Listing:product_list' %}">All</a>

         {% for category in categories %}
        <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
    {% endfor %}
    </div>
</div>

        <div class="col-lg-6">
            <div class="card-body text-center">

                <div class="bottom_line"></div>
            </div>
        </div>
        {% for product in products %}
            <div class="col-sm-6">
                <div class="card product">
                    <div class="item">
                        <div class="item-image">
                            <a href="{{ product.get_absolute_url }}">

                                <img src ="{{ product.image.url }}"alt=""
                                     class="img-fluid rounded-0">
                            </a>



                        </div>
                        <div class="item-text">
                            <div class="item-text-wrap">

                            </div>
                        </div>
                        <div class="card-body text-center">
                            {{ product.name }}
                            <hr>
                            <span>${{ product.price }}</span>

                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
{% endblock content %}

templates/product/search.html
{% extends 'base.html' %}
{% block title %}Store{% endblock %}
{% block content %}

<center>
     {%if searched %}
        <h2>You searched for {{ searched }}</h2>
         <br/>
         {% for product in products%}
            <ul class="list-group list-group-flush">

                <li  class="list-group-item" ><a href="{{ product.get_absolute_url }}" >{{ product }} {{ product.price }}$</a>




                </li>

            </ul>

         {% empty %}
            <p>Sorry, nothing was found for your {{ searched }} request </p>

         {% endfor %}
     {% else %}
        <h2>hey</h2>
     {% endif %}
    </center>

{% endblock content %}